# site-wide variables
title: Cybersecurity Innovation for Cyberinfrastructure (CICI) Project Website
email: csgrad@iupui.edu
google: https://www.nsf.gov/awardsearch/showAward?AWD_ID=1839746
github: https://github.com/iupui-soic/dynaswap

# base directory where site is hosted
baseurl: /CICI

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: An easy-to-use, flexible website template for labs, with automatic citations, GitHub tag imports, pre-built components, and more.
      background: images/background.jpg
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
